---
- name: Hardering password requirenments
  hosts: all

  tasks:
    - name: Check avalibility pwquality library
      action: "{{ package_manager }} name={{ libpam_pakages }} state=present"

    - name: Change all modules
      pamd:
        name: "{{ pwquality_path }}"
        type: password
        control: requisite
        module_path: pam_pwquality.so
        module_arguments: 'retry=3
          minlen=4
          reject_username
          enforce_for_root'
        state: updated
