---
ansible_become: yes
ansible_ssh_user            : ansible
ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa
package_manager: apt
libpam_pakages: libpam-pwquality
pwquality_path: common-password