apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
    - image: yuriig/canary:v1.1.1
      name: app

      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3

      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        periodSeconds: 2
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1
        
      ports:
        - containerPort: 8080
          name: http
