apiVersion: v1
kind: Pod
metadata:
 name: livenessprobes-v1
spec:
 containers:
   - image: yuriig/livenessprobes:v1
     name: livenessprobes-v1
     ports:
       - containerPort: 3000
         protocol: TCP
     livenessProbe:
       httpGet:
         path: /
         port: 3000
       initialDelaySeconds: 5
       failureThreshold: 3
       successThreshold: 1
